// memory.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module memory (
		input  wire [29:0]  bridge_0_avalon_master_address,         //             bridge_0_avalon_master.address
		input  wire [7:0]   bridge_0_avalon_master_burstcount,      //                                   .burstcount
		input  wire [15:0]  bridge_0_avalon_master_byteenable,      //                                   .byteenable
		input  wire         bridge_0_avalon_master_read,            //                                   .read
		output wire [127:0] bridge_0_avalon_master_readdata,        //                                   .readdata
		output wire         bridge_0_avalon_master_readdatavalid,   //                                   .readdatavalid
		output wire         bridge_0_avalon_master_waitrequest,     //                                   .waitrequest
		input  wire         bridge_0_avalon_master_write,           //                                   .write
		input  wire [127:0] bridge_0_avalon_master_writedata,       //                                   .writedata
		input  wire         clk_0,                                   //                       clk_0_clk_in.clk
		input  wire         reset_n,                                 //                 clk_0_clk_in_reset.reset_n
		output wire [0:0]   bwe_n_to_the_ssram,                      // flash_tristate_bridge_bridge_0_out.bwe_n_to_the_ssram
		output wire [0:0]   adsc_n_to_the_max2_inf,                  //                                   .adsc_n_to_the_max2_inf
		output wire [0:0]   adsc_n_to_the_ssram,                     //                                   .adsc_n_to_the_ssram
		output wire [0:0]   chipenable1_n_to_the_max2_inf,           //                                   .chipenable1_n_to_the_max2_inf
		output wire [0:0]   reset_n_to_the_ssram,                    //                                   .reset_n_to_the_ssram
		output wire [0:0]   write_n_to_the_ext_flash,                //                                   .write_n_to_the_ext_flash
		output wire [0:0]   select_n_to_the_ext_flash,               //                                   .select_n_to_the_ext_flash
		output wire [24:0]  flash_tristate_bridge_address,           //                                   .flash_tristate_bridge_address
		inout  wire [31:0]  flash_tristate_bridge_data,              //                                   .flash_tristate_bridge_data
		output wire [0:0]   reset_n_to_the_max2_inf,                 //                                   .reset_n_to_the_max2_inf
		output wire [0:0]   outputenable_n_to_the_max2_inf,          //                                   .outputenable_n_to_the_max2_inf
		output wire [3:0]   bw_n_to_the_ssram,                       //                                   .bw_n_to_the_ssram
		output wire [3:0]   bw_n_to_the_max2_inf,                    //                                   .bw_n_to_the_max2_inf
		output wire [0:0]   bwe_n_to_the_max2_inf,                   //                                   .bwe_n_to_the_max2_inf
		output wire [0:0]   read_n_to_the_ext_flash,                 //                                   .read_n_to_the_ext_flash
		output wire [0:0]   outputenable_n_to_the_ssram,             //                                   .outputenable_n_to_the_ssram
		output wire [0:0]   chipenable1_n_to_the_ssram               //                                   .chipenable1_n_to_the_ssram
	);

	wire   [24:0] flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_address_out;  // flash_tristate_bridge_pinSharer_0:flash_tristate_bridge_address -> flash_tristate_bridge_bridge_0:tcs_flash_tristate_bridge_address
	wire          flash_tristate_bridge_pinsharer_0_tcm_request;                            // flash_tristate_bridge_pinSharer_0:request -> flash_tristate_bridge_bridge_0:request
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_outputenable_n_to_the_max2_inf_out; // flash_tristate_bridge_pinSharer_0:outputenable_n_to_the_max2_inf -> flash_tristate_bridge_bridge_0:tcs_outputenable_n_to_the_max2_inf
	wire   [31:0] flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_out;     // flash_tristate_bridge_pinSharer_0:flash_tristate_bridge_data -> flash_tristate_bridge_bridge_0:tcs_flash_tristate_bridge_data
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_read_n_to_the_ext_flash_out;        // flash_tristate_bridge_pinSharer_0:read_n_to_the_ext_flash -> flash_tristate_bridge_bridge_0:tcs_read_n_to_the_ext_flash
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_reset_n_to_the_max2_inf_out;        // flash_tristate_bridge_pinSharer_0:reset_n_to_the_max2_inf -> flash_tristate_bridge_bridge_0:tcs_reset_n_to_the_max2_inf
	wire   [31:0] flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_in;      // flash_tristate_bridge_bridge_0:tcs_flash_tristate_bridge_data_in -> flash_tristate_bridge_pinSharer_0:flash_tristate_bridge_data_in
	wire    [3:0] flash_tristate_bridge_pinsharer_0_tcm_bw_n_to_the_max2_inf_out;           // flash_tristate_bridge_pinSharer_0:bw_n_to_the_max2_inf -> flash_tristate_bridge_bridge_0:tcs_bw_n_to_the_max2_inf
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_adsc_n_to_the_ssram_out;            // flash_tristate_bridge_pinSharer_0:adsc_n_to_the_ssram -> flash_tristate_bridge_bridge_0:tcs_adsc_n_to_the_ssram
	wire          flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_outen;   // flash_tristate_bridge_pinSharer_0:flash_tristate_bridge_data_outen -> flash_tristate_bridge_bridge_0:tcs_flash_tristate_bridge_data_outen
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_bwe_n_to_the_max2_inf_out;          // flash_tristate_bridge_pinSharer_0:bwe_n_to_the_max2_inf -> flash_tristate_bridge_bridge_0:tcs_bwe_n_to_the_max2_inf
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_write_n_to_the_ext_flash_out;       // flash_tristate_bridge_pinSharer_0:write_n_to_the_ext_flash -> flash_tristate_bridge_bridge_0:tcs_write_n_to_the_ext_flash
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_chipenable1_n_to_the_ssram_out;     // flash_tristate_bridge_pinSharer_0:chipenable1_n_to_the_ssram -> flash_tristate_bridge_bridge_0:tcs_chipenable1_n_to_the_ssram
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_reset_n_to_the_ssram_out;           // flash_tristate_bridge_pinSharer_0:reset_n_to_the_ssram -> flash_tristate_bridge_bridge_0:tcs_reset_n_to_the_ssram
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_adsc_n_to_the_max2_inf_out;         // flash_tristate_bridge_pinSharer_0:adsc_n_to_the_max2_inf -> flash_tristate_bridge_bridge_0:tcs_adsc_n_to_the_max2_inf
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_outputenable_n_to_the_ssram_out;    // flash_tristate_bridge_pinSharer_0:outputenable_n_to_the_ssram -> flash_tristate_bridge_bridge_0:tcs_outputenable_n_to_the_ssram
	wire          flash_tristate_bridge_pinsharer_0_tcm_grant;                              // flash_tristate_bridge_bridge_0:grant -> flash_tristate_bridge_pinSharer_0:grant
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_select_n_to_the_ext_flash_out;      // flash_tristate_bridge_pinSharer_0:select_n_to_the_ext_flash -> flash_tristate_bridge_bridge_0:tcs_select_n_to_the_ext_flash
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_chipenable1_n_to_the_max2_inf_out;  // flash_tristate_bridge_pinSharer_0:chipenable1_n_to_the_max2_inf -> flash_tristate_bridge_bridge_0:tcs_chipenable1_n_to_the_max2_inf
	wire    [3:0] flash_tristate_bridge_pinsharer_0_tcm_bw_n_to_the_ssram_out;              // flash_tristate_bridge_pinSharer_0:bw_n_to_the_ssram -> flash_tristate_bridge_bridge_0:tcs_bw_n_to_the_ssram
	wire    [0:0] flash_tristate_bridge_pinsharer_0_tcm_bwe_n_to_the_ssram_out;             // flash_tristate_bridge_pinSharer_0:bwe_n_to_the_ssram -> flash_tristate_bridge_bridge_0:tcs_bwe_n_to_the_ssram
	wire          ssram_tcm_data_outen;                                                     // ssram:tcm_data_outen -> flash_tristate_bridge_pinSharer_0:tcs0_data_outen
	wire          ssram_tcm_outputenable_n_out;                                             // ssram:tcm_outputenable_n_out -> flash_tristate_bridge_pinSharer_0:tcs0_outputenable_n_out
	wire          ssram_tcm_request;                                                        // ssram:tcm_request -> flash_tristate_bridge_pinSharer_0:tcs0_request
	wire    [3:0] ssram_tcm_byteenable_n_out;                                               // ssram:tcm_byteenable_n_out -> flash_tristate_bridge_pinSharer_0:tcs0_byteenable_n_out
	wire          ssram_tcm_write_n_out;                                                    // ssram:tcm_write_n_out -> flash_tristate_bridge_pinSharer_0:tcs0_write_n_out
	wire          ssram_tcm_begintransfer_n_out;                                            // ssram:tcm_begintransfer_n_out -> flash_tristate_bridge_pinSharer_0:tcs0_begintransfer_n_out
	wire          ssram_tcm_grant;                                                          // flash_tristate_bridge_pinSharer_0:tcs0_grant -> ssram:tcm_grant
	wire          ssram_tcm_reset_n_out;                                                    // ssram:tcm_reset_n_out -> flash_tristate_bridge_pinSharer_0:tcs0_reset_n_out
	wire          ssram_tcm_chipselect_n_out;                                               // ssram:tcm_chipselect_n_out -> flash_tristate_bridge_pinSharer_0:tcs0_chipselect_n_out
	wire   [20:0] ssram_tcm_address_out;                                                    // ssram:tcm_address_out -> flash_tristate_bridge_pinSharer_0:tcs0_address_out
	wire   [31:0] ssram_tcm_data_out;                                                       // ssram:tcm_data_out -> flash_tristate_bridge_pinSharer_0:tcs0_data_out
	wire   [31:0] ssram_tcm_data_in;                                                        // flash_tristate_bridge_pinSharer_0:tcs0_data_in -> ssram:tcm_data_in
	wire          max2_inf_tcm_data_outen;                                                  // max2_inf:tcm_data_outen -> flash_tristate_bridge_pinSharer_0:tcs1_data_outen
	wire          max2_inf_tcm_outputenable_n_out;                                          // max2_inf:tcm_outputenable_n_out -> flash_tristate_bridge_pinSharer_0:tcs1_outputenable_n_out
	wire          max2_inf_tcm_request;                                                     // max2_inf:tcm_request -> flash_tristate_bridge_pinSharer_0:tcs1_request
	wire    [3:0] max2_inf_tcm_byteenable_n_out;                                            // max2_inf:tcm_byteenable_n_out -> flash_tristate_bridge_pinSharer_0:tcs1_byteenable_n_out
	wire          max2_inf_tcm_write_n_out;                                                 // max2_inf:tcm_write_n_out -> flash_tristate_bridge_pinSharer_0:tcs1_write_n_out
	wire          max2_inf_tcm_begintransfer_n_out;                                         // max2_inf:tcm_begintransfer_n_out -> flash_tristate_bridge_pinSharer_0:tcs1_begintransfer_n_out
	wire          max2_inf_tcm_grant;                                                       // flash_tristate_bridge_pinSharer_0:tcs1_grant -> max2_inf:tcm_grant
	wire          max2_inf_tcm_reset_n_out;                                                 // max2_inf:tcm_reset_n_out -> flash_tristate_bridge_pinSharer_0:tcs1_reset_n_out
	wire          max2_inf_tcm_chipselect_n_out;                                            // max2_inf:tcm_chipselect_n_out -> flash_tristate_bridge_pinSharer_0:tcs1_chipselect_n_out
	wire   [19:0] max2_inf_tcm_address_out;                                                 // max2_inf:tcm_address_out -> flash_tristate_bridge_pinSharer_0:tcs1_address_out
	wire   [31:0] max2_inf_tcm_data_out;                                                    // max2_inf:tcm_data_out -> flash_tristate_bridge_pinSharer_0:tcs1_data_out
	wire   [31:0] max2_inf_tcm_data_in;                                                     // flash_tristate_bridge_pinSharer_0:tcs1_data_in -> max2_inf:tcm_data_in
	wire          ext_flash_tcm_data_outen;                                                 // ext_flash:tcm_data_outen -> flash_tristate_bridge_pinSharer_0:tcs2_data_outen
	wire          ext_flash_tcm_request;                                                    // ext_flash:tcm_request -> flash_tristate_bridge_pinSharer_0:tcs2_request
	wire          ext_flash_tcm_write_n_out;                                                // ext_flash:tcm_write_n_out -> flash_tristate_bridge_pinSharer_0:tcs2_write_n_out
	wire          ext_flash_tcm_read_n_out;                                                 // ext_flash:tcm_read_n_out -> flash_tristate_bridge_pinSharer_0:tcs2_read_n_out
	wire          ext_flash_tcm_grant;                                                      // flash_tristate_bridge_pinSharer_0:tcs2_grant -> ext_flash:tcm_grant
	wire          ext_flash_tcm_chipselect_n_out;                                           // ext_flash:tcm_chipselect_n_out -> flash_tristate_bridge_pinSharer_0:tcs2_chipselect_n_out
	wire   [24:0] ext_flash_tcm_address_out;                                                // ext_flash:tcm_address_out -> flash_tristate_bridge_pinSharer_0:tcs2_address_out
	wire   [15:0] ext_flash_tcm_data_out;                                                   // ext_flash:tcm_data_out -> flash_tristate_bridge_pinSharer_0:tcs2_data_out
	wire   [15:0] ext_flash_tcm_data_in;                                                    // flash_tristate_bridge_pinSharer_0:tcs2_data_in -> ext_flash:tcm_data_in
	wire   [31:0] mm_interconnect_0_ssram_uas_readdata;                                     // ssram:uas_readdata -> mm_interconnect_0:ssram_uas_readdata
	wire          mm_interconnect_0_ssram_uas_waitrequest;                                  // ssram:uas_waitrequest -> mm_interconnect_0:ssram_uas_waitrequest
	wire          mm_interconnect_0_ssram_uas_debugaccess;                                  // mm_interconnect_0:ssram_uas_debugaccess -> ssram:uas_debugaccess
	wire   [20:0] mm_interconnect_0_ssram_uas_address;                                      // mm_interconnect_0:ssram_uas_address -> ssram:uas_address
	wire          mm_interconnect_0_ssram_uas_read;                                         // mm_interconnect_0:ssram_uas_read -> ssram:uas_read
	wire    [3:0] mm_interconnect_0_ssram_uas_byteenable;                                   // mm_interconnect_0:ssram_uas_byteenable -> ssram:uas_byteenable
	wire          mm_interconnect_0_ssram_uas_readdatavalid;                                // ssram:uas_readdatavalid -> mm_interconnect_0:ssram_uas_readdatavalid
	wire          mm_interconnect_0_ssram_uas_lock;                                         // mm_interconnect_0:ssram_uas_lock -> ssram:uas_lock
	wire          mm_interconnect_0_ssram_uas_write;                                        // mm_interconnect_0:ssram_uas_write -> ssram:uas_write
	wire   [31:0] mm_interconnect_0_ssram_uas_writedata;                                    // mm_interconnect_0:ssram_uas_writedata -> ssram:uas_writedata
	wire    [2:0] mm_interconnect_0_ssram_uas_burstcount;                                   // mm_interconnect_0:ssram_uas_burstcount -> ssram:uas_burstcount
	wire   [31:0] mm_interconnect_0_max2_inf_uas_readdata;                                  // max2_inf:uas_readdata -> mm_interconnect_0:max2_inf_uas_readdata
	wire          mm_interconnect_0_max2_inf_uas_waitrequest;                               // max2_inf:uas_waitrequest -> mm_interconnect_0:max2_inf_uas_waitrequest
	wire          mm_interconnect_0_max2_inf_uas_debugaccess;                               // mm_interconnect_0:max2_inf_uas_debugaccess -> max2_inf:uas_debugaccess
	wire   [19:0] mm_interconnect_0_max2_inf_uas_address;                                   // mm_interconnect_0:max2_inf_uas_address -> max2_inf:uas_address
	wire          mm_interconnect_0_max2_inf_uas_read;                                      // mm_interconnect_0:max2_inf_uas_read -> max2_inf:uas_read
	wire    [3:0] mm_interconnect_0_max2_inf_uas_byteenable;                                // mm_interconnect_0:max2_inf_uas_byteenable -> max2_inf:uas_byteenable
	wire          mm_interconnect_0_max2_inf_uas_readdatavalid;                             // max2_inf:uas_readdatavalid -> mm_interconnect_0:max2_inf_uas_readdatavalid
	wire          mm_interconnect_0_max2_inf_uas_lock;                                      // mm_interconnect_0:max2_inf_uas_lock -> max2_inf:uas_lock
	wire          mm_interconnect_0_max2_inf_uas_write;                                     // mm_interconnect_0:max2_inf_uas_write -> max2_inf:uas_write
	wire   [31:0] mm_interconnect_0_max2_inf_uas_writedata;                                 // mm_interconnect_0:max2_inf_uas_writedata -> max2_inf:uas_writedata
	wire    [2:0] mm_interconnect_0_max2_inf_uas_burstcount;                                // mm_interconnect_0:max2_inf_uas_burstcount -> max2_inf:uas_burstcount
	wire   [15:0] mm_interconnect_0_ext_flash_uas_readdata;                                 // ext_flash:uas_readdata -> mm_interconnect_0:ext_flash_uas_readdata
	wire          mm_interconnect_0_ext_flash_uas_waitrequest;                              // ext_flash:uas_waitrequest -> mm_interconnect_0:ext_flash_uas_waitrequest
	wire          mm_interconnect_0_ext_flash_uas_debugaccess;                              // mm_interconnect_0:ext_flash_uas_debugaccess -> ext_flash:uas_debugaccess
	wire   [24:0] mm_interconnect_0_ext_flash_uas_address;                                  // mm_interconnect_0:ext_flash_uas_address -> ext_flash:uas_address
	wire          mm_interconnect_0_ext_flash_uas_read;                                     // mm_interconnect_0:ext_flash_uas_read -> ext_flash:uas_read
	wire    [1:0] mm_interconnect_0_ext_flash_uas_byteenable;                               // mm_interconnect_0:ext_flash_uas_byteenable -> ext_flash:uas_byteenable
	wire          mm_interconnect_0_ext_flash_uas_readdatavalid;                            // ext_flash:uas_readdatavalid -> mm_interconnect_0:ext_flash_uas_readdatavalid
	wire          mm_interconnect_0_ext_flash_uas_lock;                                     // mm_interconnect_0:ext_flash_uas_lock -> ext_flash:uas_lock
	wire          mm_interconnect_0_ext_flash_uas_write;                                    // mm_interconnect_0:ext_flash_uas_write -> ext_flash:uas_write
	wire   [15:0] mm_interconnect_0_ext_flash_uas_writedata;                                // mm_interconnect_0:ext_flash_uas_writedata -> ext_flash:uas_writedata
	wire    [1:0] mm_interconnect_0_ext_flash_uas_burstcount;                               // mm_interconnect_0:ext_flash_uas_burstcount -> ext_flash:uas_burstcount
	wire          rst_controller_reset_out_reset;                                           // rst_controller:reset_out -> [bridge_0:reset, ext_flash:reset_reset, flash_tristate_bridge_bridge_0:reset, flash_tristate_bridge_pinSharer_0:reset_reset, max2_inf:reset_reset, mm_interconnect_0:bridge_0_reset_reset_bridge_in_reset_reset, ssram:reset_reset]

	memory_ext_flash #(
		.TCM_ADDRESS_W                  (25),
		.TCM_DATA_W                     (16),
		.TCM_BYTEENABLE_W               (2),
		.TCM_READ_WAIT                  (100),
		.TCM_WRITE_WAIT                 (100),
		.TCM_SETUP_WAIT                 (25),
		.TCM_DATA_HOLD                  (20),
		.TCM_TURNAROUND_TIME            (2),
		.TCM_TIMING_UNITS               (0),
		.TCM_READLATENCY                (2),
		.TCM_SYMBOLS_PER_WORD           (2),
		.USE_READDATA                   (1),
		.USE_WRITEDATA                  (1),
		.USE_READ                       (1),
		.USE_WRITE                      (1),
		.USE_BYTEENABLE                 (0),
		.USE_CHIPSELECT                 (1),
		.USE_LOCK                       (0),
		.USE_ADDRESS                    (1),
		.USE_WAITREQUEST                (0),
		.USE_WRITEBYTEENABLE            (0),
		.USE_OUTPUTENABLE               (0),
		.USE_RESETREQUEST               (0),
		.USE_IRQ                        (0),
		.USE_RESET_OUTPUT               (0),
		.ACTIVE_LOW_READ                (1),
		.ACTIVE_LOW_LOCK                (0),
		.ACTIVE_LOW_WRITE               (1),
		.ACTIVE_LOW_CHIPSELECT          (1),
		.ACTIVE_LOW_BYTEENABLE          (0),
		.ACTIVE_LOW_OUTPUTENABLE        (0),
		.ACTIVE_LOW_WRITEBYTEENABLE     (0),
		.ACTIVE_LOW_WAITREQUEST         (0),
		.ACTIVE_LOW_BEGINTRANSFER       (0),
		.CHIPSELECT_THROUGH_READLATENCY (0)
	) ext_flash (
		.clk_clk              (clk_0),                                         //   clk.clk
		.reset_reset          (rst_controller_reset_out_reset),                // reset.reset
		.uas_address          (mm_interconnect_0_ext_flash_uas_address),       //   uas.address
		.uas_burstcount       (mm_interconnect_0_ext_flash_uas_burstcount),    //      .burstcount
		.uas_read             (mm_interconnect_0_ext_flash_uas_read),          //      .read
		.uas_write            (mm_interconnect_0_ext_flash_uas_write),         //      .write
		.uas_waitrequest      (mm_interconnect_0_ext_flash_uas_waitrequest),   //      .waitrequest
		.uas_readdatavalid    (mm_interconnect_0_ext_flash_uas_readdatavalid), //      .readdatavalid
		.uas_byteenable       (mm_interconnect_0_ext_flash_uas_byteenable),    //      .byteenable
		.uas_readdata         (mm_interconnect_0_ext_flash_uas_readdata),      //      .readdata
		.uas_writedata        (mm_interconnect_0_ext_flash_uas_writedata),     //      .writedata
		.uas_lock             (mm_interconnect_0_ext_flash_uas_lock),          //      .lock
		.uas_debugaccess      (mm_interconnect_0_ext_flash_uas_debugaccess),   //      .debugaccess
		.tcm_write_n_out      (ext_flash_tcm_write_n_out),                     //   tcm.write_n_out
		.tcm_read_n_out       (ext_flash_tcm_read_n_out),                      //      .read_n_out
		.tcm_chipselect_n_out (ext_flash_tcm_chipselect_n_out),                //      .chipselect_n_out
		.tcm_request          (ext_flash_tcm_request),                         //      .request
		.tcm_grant            (ext_flash_tcm_grant),                           //      .grant
		.tcm_address_out      (ext_flash_tcm_address_out),                     //      .address_out
		.tcm_data_out         (ext_flash_tcm_data_out),                        //      .data_out
		.tcm_data_outen       (ext_flash_tcm_data_outen),                      //      .data_outen
		.tcm_data_in          (ext_flash_tcm_data_in)                          //      .data_in
	);

	memory_flash_tristate_bridge_bridge_0 flash_tristate_bridge_bridge_0 (
		.clk                                  (clk_0),                                                                    //   clk.clk
		.reset                                (rst_controller_reset_out_reset),                                           // reset.reset
		.request                              (flash_tristate_bridge_pinsharer_0_tcm_request),                            //   tcs.request
		.grant                                (flash_tristate_bridge_pinsharer_0_tcm_grant),                              //      .grant
		.tcs_bwe_n_to_the_ssram               (flash_tristate_bridge_pinsharer_0_tcm_bwe_n_to_the_ssram_out),             //      .bwe_n_to_the_ssram_out
		.tcs_adsc_n_to_the_max2_inf           (flash_tristate_bridge_pinsharer_0_tcm_adsc_n_to_the_max2_inf_out),         //      .adsc_n_to_the_max2_inf_out
		.tcs_adsc_n_to_the_ssram              (flash_tristate_bridge_pinsharer_0_tcm_adsc_n_to_the_ssram_out),            //      .adsc_n_to_the_ssram_out
		.tcs_chipenable1_n_to_the_max2_inf    (flash_tristate_bridge_pinsharer_0_tcm_chipenable1_n_to_the_max2_inf_out),  //      .chipenable1_n_to_the_max2_inf_out
		.tcs_reset_n_to_the_ssram             (flash_tristate_bridge_pinsharer_0_tcm_reset_n_to_the_ssram_out),           //      .reset_n_to_the_ssram_out
		.tcs_write_n_to_the_ext_flash         (flash_tristate_bridge_pinsharer_0_tcm_write_n_to_the_ext_flash_out),       //      .write_n_to_the_ext_flash_out
		.tcs_select_n_to_the_ext_flash        (flash_tristate_bridge_pinsharer_0_tcm_select_n_to_the_ext_flash_out),      //      .select_n_to_the_ext_flash_out
		.tcs_flash_tristate_bridge_address    (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_address_out),  //      .flash_tristate_bridge_address_out
		.tcs_flash_tristate_bridge_data       (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_out),     //      .flash_tristate_bridge_data_out
		.tcs_flash_tristate_bridge_data_outen (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_outen),   //      .flash_tristate_bridge_data_outen
		.tcs_flash_tristate_bridge_data_in    (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_in),      //      .flash_tristate_bridge_data_in
		.tcs_reset_n_to_the_max2_inf          (flash_tristate_bridge_pinsharer_0_tcm_reset_n_to_the_max2_inf_out),        //      .reset_n_to_the_max2_inf_out
		.tcs_outputenable_n_to_the_max2_inf   (flash_tristate_bridge_pinsharer_0_tcm_outputenable_n_to_the_max2_inf_out), //      .outputenable_n_to_the_max2_inf_out
		.tcs_bw_n_to_the_ssram                (flash_tristate_bridge_pinsharer_0_tcm_bw_n_to_the_ssram_out),              //      .bw_n_to_the_ssram_out
		.tcs_bw_n_to_the_max2_inf             (flash_tristate_bridge_pinsharer_0_tcm_bw_n_to_the_max2_inf_out),           //      .bw_n_to_the_max2_inf_out
		.tcs_bwe_n_to_the_max2_inf            (flash_tristate_bridge_pinsharer_0_tcm_bwe_n_to_the_max2_inf_out),          //      .bwe_n_to_the_max2_inf_out
		.tcs_read_n_to_the_ext_flash          (flash_tristate_bridge_pinsharer_0_tcm_read_n_to_the_ext_flash_out),        //      .read_n_to_the_ext_flash_out
		.tcs_outputenable_n_to_the_ssram      (flash_tristate_bridge_pinsharer_0_tcm_outputenable_n_to_the_ssram_out),    //      .outputenable_n_to_the_ssram_out
		.tcs_chipenable1_n_to_the_ssram       (flash_tristate_bridge_pinsharer_0_tcm_chipenable1_n_to_the_ssram_out),     //      .chipenable1_n_to_the_ssram_out
		.bwe_n_to_the_ssram                   (bwe_n_to_the_ssram),                                                       //   out.bwe_n_to_the_ssram
		.adsc_n_to_the_max2_inf               (adsc_n_to_the_max2_inf),                                                   //      .adsc_n_to_the_max2_inf
		.adsc_n_to_the_ssram                  (adsc_n_to_the_ssram),                                                      //      .adsc_n_to_the_ssram
		.chipenable1_n_to_the_max2_inf        (chipenable1_n_to_the_max2_inf),                                            //      .chipenable1_n_to_the_max2_inf
		.reset_n_to_the_ssram                 (reset_n_to_the_ssram),                                                     //      .reset_n_to_the_ssram
		.write_n_to_the_ext_flash             (write_n_to_the_ext_flash),                                                 //      .write_n_to_the_ext_flash
		.select_n_to_the_ext_flash            (select_n_to_the_ext_flash),                                                //      .select_n_to_the_ext_flash
		.flash_tristate_bridge_address        (flash_tristate_bridge_address),                                            //      .flash_tristate_bridge_address
		.flash_tristate_bridge_data           (flash_tristate_bridge_data),                                               //      .flash_tristate_bridge_data
		.reset_n_to_the_max2_inf              (reset_n_to_the_max2_inf),                                                  //      .reset_n_to_the_max2_inf
		.outputenable_n_to_the_max2_inf       (outputenable_n_to_the_max2_inf),                                           //      .outputenable_n_to_the_max2_inf
		.bw_n_to_the_ssram                    (bw_n_to_the_ssram),                                                        //      .bw_n_to_the_ssram
		.bw_n_to_the_max2_inf                 (bw_n_to_the_max2_inf),                                                     //      .bw_n_to_the_max2_inf
		.bwe_n_to_the_max2_inf                (bwe_n_to_the_max2_inf),                                                    //      .bwe_n_to_the_max2_inf
		.read_n_to_the_ext_flash              (read_n_to_the_ext_flash),                                                  //      .read_n_to_the_ext_flash
		.outputenable_n_to_the_ssram          (outputenable_n_to_the_ssram),                                              //      .outputenable_n_to_the_ssram
		.chipenable1_n_to_the_ssram           (chipenable1_n_to_the_ssram)                                                //      .chipenable1_n_to_the_ssram
	);

	memory_flash_tristate_bridge_pinSharer_0 flash_tristate_bridge_pinsharer_0 (
		.clk_clk                          (clk_0),                                                                    //   clk.clk
		.reset_reset                      (rst_controller_reset_out_reset),                                           // reset.reset
		.request                          (flash_tristate_bridge_pinsharer_0_tcm_request),                            //   tcm.request
		.grant                            (flash_tristate_bridge_pinsharer_0_tcm_grant),                              //      .grant
		.read_n_to_the_ext_flash          (flash_tristate_bridge_pinsharer_0_tcm_read_n_to_the_ext_flash_out),        //      .read_n_to_the_ext_flash_out
		.write_n_to_the_ext_flash         (flash_tristate_bridge_pinsharer_0_tcm_write_n_to_the_ext_flash_out),       //      .write_n_to_the_ext_flash_out
		.select_n_to_the_ext_flash        (flash_tristate_bridge_pinsharer_0_tcm_select_n_to_the_ext_flash_out),      //      .select_n_to_the_ext_flash_out
		.chipenable1_n_to_the_max2_inf    (flash_tristate_bridge_pinsharer_0_tcm_chipenable1_n_to_the_max2_inf_out),  //      .chipenable1_n_to_the_max2_inf_out
		.bw_n_to_the_max2_inf             (flash_tristate_bridge_pinsharer_0_tcm_bw_n_to_the_max2_inf_out),           //      .bw_n_to_the_max2_inf_out
		.outputenable_n_to_the_max2_inf   (flash_tristate_bridge_pinsharer_0_tcm_outputenable_n_to_the_max2_inf_out), //      .outputenable_n_to_the_max2_inf_out
		.bwe_n_to_the_max2_inf            (flash_tristate_bridge_pinsharer_0_tcm_bwe_n_to_the_max2_inf_out),          //      .bwe_n_to_the_max2_inf_out
		.reset_n_to_the_max2_inf          (flash_tristate_bridge_pinsharer_0_tcm_reset_n_to_the_max2_inf_out),        //      .reset_n_to_the_max2_inf_out
		.adsc_n_to_the_max2_inf           (flash_tristate_bridge_pinsharer_0_tcm_adsc_n_to_the_max2_inf_out),         //      .adsc_n_to_the_max2_inf_out
		.chipenable1_n_to_the_ssram       (flash_tristate_bridge_pinsharer_0_tcm_chipenable1_n_to_the_ssram_out),     //      .chipenable1_n_to_the_ssram_out
		.bw_n_to_the_ssram                (flash_tristate_bridge_pinsharer_0_tcm_bw_n_to_the_ssram_out),              //      .bw_n_to_the_ssram_out
		.outputenable_n_to_the_ssram      (flash_tristate_bridge_pinsharer_0_tcm_outputenable_n_to_the_ssram_out),    //      .outputenable_n_to_the_ssram_out
		.bwe_n_to_the_ssram               (flash_tristate_bridge_pinsharer_0_tcm_bwe_n_to_the_ssram_out),             //      .bwe_n_to_the_ssram_out
		.flash_tristate_bridge_data       (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_out),     //      .flash_tristate_bridge_data_out
		.flash_tristate_bridge_data_in    (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_in),      //      .flash_tristate_bridge_data_in
		.flash_tristate_bridge_data_outen (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_data_outen),   //      .flash_tristate_bridge_data_outen
		.flash_tristate_bridge_address    (flash_tristate_bridge_pinsharer_0_tcm_flash_tristate_bridge_address_out),  //      .flash_tristate_bridge_address_out
		.reset_n_to_the_ssram             (flash_tristate_bridge_pinsharer_0_tcm_reset_n_to_the_ssram_out),           //      .reset_n_to_the_ssram_out
		.adsc_n_to_the_ssram              (flash_tristate_bridge_pinsharer_0_tcm_adsc_n_to_the_ssram_out),            //      .adsc_n_to_the_ssram_out
		.tcs0_request                     (ssram_tcm_request),                                                        //  tcs0.request
		.tcs0_grant                       (ssram_tcm_grant),                                                          //      .grant
		.tcs0_chipselect_n_out            (ssram_tcm_chipselect_n_out),                                               //      .chipselect_n_out
		.tcs0_byteenable_n_out            (ssram_tcm_byteenable_n_out),                                               //      .byteenable_n_out
		.tcs0_outputenable_n_out          (ssram_tcm_outputenable_n_out),                                             //      .outputenable_n_out
		.tcs0_write_n_out                 (ssram_tcm_write_n_out),                                                    //      .write_n_out
		.tcs0_data_out                    (ssram_tcm_data_out),                                                       //      .data_out
		.tcs0_data_in                     (ssram_tcm_data_in),                                                        //      .data_in
		.tcs0_data_outen                  (ssram_tcm_data_outen),                                                     //      .data_outen
		.tcs0_address_out                 (ssram_tcm_address_out),                                                    //      .address_out
		.tcs0_reset_n_out                 (ssram_tcm_reset_n_out),                                                    //      .reset_n_out
		.tcs0_begintransfer_n_out         (ssram_tcm_begintransfer_n_out),                                            //      .begintransfer_n_out
		.tcs1_request                     (max2_inf_tcm_request),                                                     //  tcs1.request
		.tcs1_grant                       (max2_inf_tcm_grant),                                                       //      .grant
		.tcs1_chipselect_n_out            (max2_inf_tcm_chipselect_n_out),                                            //      .chipselect_n_out
		.tcs1_byteenable_n_out            (max2_inf_tcm_byteenable_n_out),                                            //      .byteenable_n_out
		.tcs1_outputenable_n_out          (max2_inf_tcm_outputenable_n_out),                                          //      .outputenable_n_out
		.tcs1_write_n_out                 (max2_inf_tcm_write_n_out),                                                 //      .write_n_out
		.tcs1_data_out                    (max2_inf_tcm_data_out),                                                    //      .data_out
		.tcs1_data_in                     (max2_inf_tcm_data_in),                                                     //      .data_in
		.tcs1_data_outen                  (max2_inf_tcm_data_outen),                                                  //      .data_outen
		.tcs1_address_out                 (max2_inf_tcm_address_out),                                                 //      .address_out
		.tcs1_reset_n_out                 (max2_inf_tcm_reset_n_out),                                                 //      .reset_n_out
		.tcs1_begintransfer_n_out         (max2_inf_tcm_begintransfer_n_out),                                         //      .begintransfer_n_out
		.tcs2_request                     (ext_flash_tcm_request),                                                    //  tcs2.request
		.tcs2_grant                       (ext_flash_tcm_grant),                                                      //      .grant
		.tcs2_address_out                 (ext_flash_tcm_address_out),                                                //      .address_out
		.tcs2_read_n_out                  (ext_flash_tcm_read_n_out),                                                 //      .read_n_out
		.tcs2_write_n_out                 (ext_flash_tcm_write_n_out),                                                //      .write_n_out
		.tcs2_data_out                    (ext_flash_tcm_data_out),                                                   //      .data_out
		.tcs2_data_in                     (ext_flash_tcm_data_in),                                                    //      .data_in
		.tcs2_data_outen                  (ext_flash_tcm_data_outen),                                                 //      .data_outen
		.tcs2_chipselect_n_out            (ext_flash_tcm_chipselect_n_out)                                            //      .chipselect_n_out
	);

	memory_max2_inf #(
		.TCM_ADDRESS_W                  (20),
		.TCM_DATA_W                     (32),
		.TCM_BYTEENABLE_W               (4),
		.TCM_READ_WAIT                  (0),
		.TCM_WRITE_WAIT                 (0),
		.TCM_SETUP_WAIT                 (0),
		.TCM_DATA_HOLD                  (0),
		.TCM_TURNAROUND_TIME            (2),
		.TCM_TIMING_UNITS               (1),
		.TCM_READLATENCY                (4),
		.TCM_SYMBOLS_PER_WORD           (4),
		.USE_READDATA                   (1),
		.USE_WRITEDATA                  (1),
		.USE_READ                       (0),
		.USE_WRITE                      (1),
		.USE_BYTEENABLE                 (1),
		.USE_CHIPSELECT                 (1),
		.USE_LOCK                       (0),
		.USE_ADDRESS                    (1),
		.USE_WAITREQUEST                (0),
		.USE_WRITEBYTEENABLE            (0),
		.USE_OUTPUTENABLE               (1),
		.USE_RESETREQUEST               (0),
		.USE_IRQ                        (0),
		.USE_RESET_OUTPUT               (1),
		.ACTIVE_LOW_READ                (0),
		.ACTIVE_LOW_LOCK                (0),
		.ACTIVE_LOW_WRITE               (1),
		.ACTIVE_LOW_CHIPSELECT          (1),
		.ACTIVE_LOW_BYTEENABLE          (1),
		.ACTIVE_LOW_OUTPUTENABLE        (1),
		.ACTIVE_LOW_WRITEBYTEENABLE     (0),
		.ACTIVE_LOW_WAITREQUEST         (0),
		.ACTIVE_LOW_BEGINTRANSFER       (1),
		.CHIPSELECT_THROUGH_READLATENCY (1)
	) max2_inf (
		.clk_clk                 (clk_0),                                        //   clk.clk
		.reset_reset             (rst_controller_reset_out_reset),               // reset.reset
		.uas_address             (mm_interconnect_0_max2_inf_uas_address),       //   uas.address
		.uas_burstcount          (mm_interconnect_0_max2_inf_uas_burstcount),    //      .burstcount
		.uas_read                (mm_interconnect_0_max2_inf_uas_read),          //      .read
		.uas_write               (mm_interconnect_0_max2_inf_uas_write),         //      .write
		.uas_waitrequest         (mm_interconnect_0_max2_inf_uas_waitrequest),   //      .waitrequest
		.uas_readdatavalid       (mm_interconnect_0_max2_inf_uas_readdatavalid), //      .readdatavalid
		.uas_byteenable          (mm_interconnect_0_max2_inf_uas_byteenable),    //      .byteenable
		.uas_readdata            (mm_interconnect_0_max2_inf_uas_readdata),      //      .readdata
		.uas_writedata           (mm_interconnect_0_max2_inf_uas_writedata),     //      .writedata
		.uas_lock                (mm_interconnect_0_max2_inf_uas_lock),          //      .lock
		.uas_debugaccess         (mm_interconnect_0_max2_inf_uas_debugaccess),   //      .debugaccess
		.tcm_write_n_out         (max2_inf_tcm_write_n_out),                     //   tcm.write_n_out
		.tcm_begintransfer_n_out (max2_inf_tcm_begintransfer_n_out),             //      .begintransfer_n_out
		.tcm_chipselect_n_out    (max2_inf_tcm_chipselect_n_out),                //      .chipselect_n_out
		.tcm_outputenable_n_out  (max2_inf_tcm_outputenable_n_out),              //      .outputenable_n_out
		.tcm_reset_n_out         (max2_inf_tcm_reset_n_out),                     //      .reset_n_out
		.tcm_request             (max2_inf_tcm_request),                         //      .request
		.tcm_grant               (max2_inf_tcm_grant),                           //      .grant
		.tcm_address_out         (max2_inf_tcm_address_out),                     //      .address_out
		.tcm_byteenable_n_out    (max2_inf_tcm_byteenable_n_out),                //      .byteenable_n_out
		.tcm_data_out            (max2_inf_tcm_data_out),                        //      .data_out
		.tcm_data_outen          (max2_inf_tcm_data_outen),                      //      .data_outen
		.tcm_data_in             (max2_inf_tcm_data_in)                          //      .data_in
	);

	memory_ssram #(
		.TCM_ADDRESS_W                  (21),
		.TCM_DATA_W                     (32),
		.TCM_BYTEENABLE_W               (4),
		.TCM_READ_WAIT                  (0),
		.TCM_WRITE_WAIT                 (0),
		.TCM_SETUP_WAIT                 (0),
		.TCM_DATA_HOLD                  (0),
		.TCM_TURNAROUND_TIME            (2),
		.TCM_TIMING_UNITS               (1),
		.TCM_READLATENCY                (4),
		.TCM_SYMBOLS_PER_WORD           (4),
		.USE_READDATA                   (1),
		.USE_WRITEDATA                  (1),
		.USE_READ                       (0),
		.USE_WRITE                      (1),
		.USE_BYTEENABLE                 (1),
		.USE_CHIPSELECT                 (1),
		.USE_LOCK                       (0),
		.USE_ADDRESS                    (1),
		.USE_WAITREQUEST                (0),
		.USE_WRITEBYTEENABLE            (0),
		.USE_OUTPUTENABLE               (1),
		.USE_RESETREQUEST               (0),
		.USE_IRQ                        (0),
		.USE_RESET_OUTPUT               (1),
		.ACTIVE_LOW_READ                (0),
		.ACTIVE_LOW_LOCK                (0),
		.ACTIVE_LOW_WRITE               (1),
		.ACTIVE_LOW_CHIPSELECT          (1),
		.ACTIVE_LOW_BYTEENABLE          (1),
		.ACTIVE_LOW_OUTPUTENABLE        (1),
		.ACTIVE_LOW_WRITEBYTEENABLE     (0),
		.ACTIVE_LOW_WAITREQUEST         (0),
		.ACTIVE_LOW_BEGINTRANSFER       (1),
		.CHIPSELECT_THROUGH_READLATENCY (1)
	) ssram (
		.clk_clk                 (clk_0),                                     //   clk.clk
		.reset_reset             (rst_controller_reset_out_reset),            // reset.reset
		.uas_address             (mm_interconnect_0_ssram_uas_address),       //   uas.address
		.uas_burstcount          (mm_interconnect_0_ssram_uas_burstcount),    //      .burstcount
		.uas_read                (mm_interconnect_0_ssram_uas_read),          //      .read
		.uas_write               (mm_interconnect_0_ssram_uas_write),         //      .write
		.uas_waitrequest         (mm_interconnect_0_ssram_uas_waitrequest),   //      .waitrequest
		.uas_readdatavalid       (mm_interconnect_0_ssram_uas_readdatavalid), //      .readdatavalid
		.uas_byteenable          (mm_interconnect_0_ssram_uas_byteenable),    //      .byteenable
		.uas_readdata            (mm_interconnect_0_ssram_uas_readdata),      //      .readdata
		.uas_writedata           (mm_interconnect_0_ssram_uas_writedata),     //      .writedata
		.uas_lock                (mm_interconnect_0_ssram_uas_lock),          //      .lock
		.uas_debugaccess         (mm_interconnect_0_ssram_uas_debugaccess),   //      .debugaccess
		.tcm_write_n_out         (ssram_tcm_write_n_out),                     //   tcm.write_n_out
		.tcm_begintransfer_n_out (ssram_tcm_begintransfer_n_out),             //      .begintransfer_n_out
		.tcm_chipselect_n_out    (ssram_tcm_chipselect_n_out),                //      .chipselect_n_out
		.tcm_outputenable_n_out  (ssram_tcm_outputenable_n_out),              //      .outputenable_n_out
		.tcm_reset_n_out         (ssram_tcm_reset_n_out),                     //      .reset_n_out
		.tcm_request             (ssram_tcm_request),                         //      .request
		.tcm_grant               (ssram_tcm_grant),                           //      .grant
		.tcm_address_out         (ssram_tcm_address_out),                     //      .address_out
		.tcm_byteenable_n_out    (ssram_tcm_byteenable_n_out),                //      .byteenable_n_out
		.tcm_data_out            (ssram_tcm_data_out),                        //      .data_out
		.tcm_data_outen          (ssram_tcm_data_outen),                      //      .data_outen
		.tcm_data_in             (ssram_tcm_data_in)                          //      .data_in
	);

	memory_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                              (clk_0),                                         //                            clk_0_clk.clk
		.bridge_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                // bridge_0_reset_reset_bridge_in_reset.reset
		.bridge_0_avalon_master_address             (bridge_0_avalon_master_address),                //               bridge_0_avalon_master.address
		.bridge_0_avalon_master_waitrequest         (bridge_0_avalon_master_waitrequest),            //                                     .waitrequest
		.bridge_0_avalon_master_burstcount          (bridge_0_avalon_master_burstcount),             //                                     .burstcount
		.bridge_0_avalon_master_byteenable          (bridge_0_avalon_master_byteenable),             //                                     .byteenable
		.bridge_0_avalon_master_read                (bridge_0_avalon_master_read),                   //                                     .read
		.bridge_0_avalon_master_readdata            (bridge_0_avalon_master_readdata),               //                                     .readdata
		.bridge_0_avalon_master_readdatavalid       (bridge_0_avalon_master_readdatavalid),          //                                     .readdatavalid
		.bridge_0_avalon_master_write               (bridge_0_avalon_master_write),                  //                                     .write
		.bridge_0_avalon_master_writedata           (bridge_0_avalon_master_writedata),              //                                     .writedata
		.ext_flash_uas_address                      (mm_interconnect_0_ext_flash_uas_address),       //                        ext_flash_uas.address
		.ext_flash_uas_write                        (mm_interconnect_0_ext_flash_uas_write),         //                                     .write
		.ext_flash_uas_read                         (mm_interconnect_0_ext_flash_uas_read),          //                                     .read
		.ext_flash_uas_readdata                     (mm_interconnect_0_ext_flash_uas_readdata),      //                                     .readdata
		.ext_flash_uas_writedata                    (mm_interconnect_0_ext_flash_uas_writedata),     //                                     .writedata
		.ext_flash_uas_burstcount                   (mm_interconnect_0_ext_flash_uas_burstcount),    //                                     .burstcount
		.ext_flash_uas_byteenable                   (mm_interconnect_0_ext_flash_uas_byteenable),    //                                     .byteenable
		.ext_flash_uas_readdatavalid                (mm_interconnect_0_ext_flash_uas_readdatavalid), //                                     .readdatavalid
		.ext_flash_uas_waitrequest                  (mm_interconnect_0_ext_flash_uas_waitrequest),   //                                     .waitrequest
		.ext_flash_uas_lock                         (mm_interconnect_0_ext_flash_uas_lock),          //                                     .lock
		.ext_flash_uas_debugaccess                  (mm_interconnect_0_ext_flash_uas_debugaccess),   //                                     .debugaccess
		.max2_inf_uas_address                       (mm_interconnect_0_max2_inf_uas_address),        //                         max2_inf_uas.address
		.max2_inf_uas_write                         (mm_interconnect_0_max2_inf_uas_write),          //                                     .write
		.max2_inf_uas_read                          (mm_interconnect_0_max2_inf_uas_read),           //                                     .read
		.max2_inf_uas_readdata                      (mm_interconnect_0_max2_inf_uas_readdata),       //                                     .readdata
		.max2_inf_uas_writedata                     (mm_interconnect_0_max2_inf_uas_writedata),      //                                     .writedata
		.max2_inf_uas_burstcount                    (mm_interconnect_0_max2_inf_uas_burstcount),     //                                     .burstcount
		.max2_inf_uas_byteenable                    (mm_interconnect_0_max2_inf_uas_byteenable),     //                                     .byteenable
		.max2_inf_uas_readdatavalid                 (mm_interconnect_0_max2_inf_uas_readdatavalid),  //                                     .readdatavalid
		.max2_inf_uas_waitrequest                   (mm_interconnect_0_max2_inf_uas_waitrequest),    //                                     .waitrequest
		.max2_inf_uas_lock                          (mm_interconnect_0_max2_inf_uas_lock),           //                                     .lock
		.max2_inf_uas_debugaccess                   (mm_interconnect_0_max2_inf_uas_debugaccess),    //                                     .debugaccess
		.ssram_uas_address                          (mm_interconnect_0_ssram_uas_address),           //                            ssram_uas.address
		.ssram_uas_write                            (mm_interconnect_0_ssram_uas_write),             //                                     .write
		.ssram_uas_read                             (mm_interconnect_0_ssram_uas_read),              //                                     .read
		.ssram_uas_readdata                         (mm_interconnect_0_ssram_uas_readdata),          //                                     .readdata
		.ssram_uas_writedata                        (mm_interconnect_0_ssram_uas_writedata),         //                                     .writedata
		.ssram_uas_burstcount                       (mm_interconnect_0_ssram_uas_burstcount),        //                                     .burstcount
		.ssram_uas_byteenable                       (mm_interconnect_0_ssram_uas_byteenable),        //                                     .byteenable
		.ssram_uas_readdatavalid                    (mm_interconnect_0_ssram_uas_readdatavalid),     //                                     .readdatavalid
		.ssram_uas_waitrequest                      (mm_interconnect_0_ssram_uas_waitrequest),       //                                     .waitrequest
		.ssram_uas_lock                             (mm_interconnect_0_ssram_uas_lock),              //                                     .lock
		.ssram_uas_debugaccess                      (mm_interconnect_0_ssram_uas_debugaccess)        //                                     .debugaccess
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_n),                       // reset_in0.reset
		.clk            (clk_0),                          //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
