// memory_flash_tristate_bridge_pinSharer_0.v

// This file was auto-generated from altera_tristate_conduit_pin_sharer_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module memory_flash_tristate_bridge_pinSharer_0 (
		input  wire        clk_clk,                          //   clk.clk
		input  wire        reset_reset,                      // reset.reset
		output wire        request,                          //   tcm.request
		input  wire        grant,                            //      .grant
		output wire [0:0]  read_n_to_the_ext_flash,          //      .read_n_to_the_ext_flash_out
		output wire [0:0]  write_n_to_the_ext_flash,         //      .write_n_to_the_ext_flash_out
		output wire [0:0]  select_n_to_the_ext_flash,        //      .select_n_to_the_ext_flash_out
		output wire [0:0]  chipenable1_n_to_the_max2_inf,    //      .chipenable1_n_to_the_max2_inf_out
		output wire [3:0]  bw_n_to_the_max2_inf,             //      .bw_n_to_the_max2_inf_out
		output wire [0:0]  outputenable_n_to_the_max2_inf,   //      .outputenable_n_to_the_max2_inf_out
		output wire [0:0]  bwe_n_to_the_max2_inf,            //      .bwe_n_to_the_max2_inf_out
		output wire [0:0]  reset_n_to_the_max2_inf,          //      .reset_n_to_the_max2_inf_out
		output wire [0:0]  adsc_n_to_the_max2_inf,           //      .adsc_n_to_the_max2_inf_out
		output wire [0:0]  chipenable1_n_to_the_ssram,       //      .chipenable1_n_to_the_ssram_out
		output wire [3:0]  bw_n_to_the_ssram,                //      .bw_n_to_the_ssram_out
		output wire [0:0]  outputenable_n_to_the_ssram,      //      .outputenable_n_to_the_ssram_out
		output wire [0:0]  bwe_n_to_the_ssram,               //      .bwe_n_to_the_ssram_out
		output wire [31:0] flash_tristate_bridge_data,       //      .flash_tristate_bridge_data_out
		input  wire [31:0] flash_tristate_bridge_data_in,    //      .flash_tristate_bridge_data_in
		output wire        flash_tristate_bridge_data_outen, //      .flash_tristate_bridge_data_outen
		output wire [24:0] flash_tristate_bridge_address,    //      .flash_tristate_bridge_address_out
		output wire [0:0]  reset_n_to_the_ssram,             //      .reset_n_to_the_ssram_out
		output wire [0:0]  adsc_n_to_the_ssram,              //      .adsc_n_to_the_ssram_out
		input  wire        tcs0_request,                     //  tcs0.request
		output wire        tcs0_grant,                       //      .grant
		input  wire [0:0]  tcs0_chipselect_n_out,            //      .chipselect_n_out
		input  wire [3:0]  tcs0_byteenable_n_out,            //      .byteenable_n_out
		input  wire [0:0]  tcs0_outputenable_n_out,          //      .outputenable_n_out
		input  wire [0:0]  tcs0_write_n_out,                 //      .write_n_out
		input  wire [31:0] tcs0_data_out,                    //      .data_out
		output wire [31:0] tcs0_data_in,                     //      .data_in
		input  wire        tcs0_data_outen,                  //      .data_outen
		input  wire [20:0] tcs0_address_out,                 //      .address_out
		input  wire [0:0]  tcs0_reset_n_out,                 //      .reset_n_out
		input  wire [0:0]  tcs0_begintransfer_n_out,         //      .begintransfer_n_out
		input  wire        tcs1_request,                     //  tcs1.request
		output wire        tcs1_grant,                       //      .grant
		input  wire [0:0]  tcs1_chipselect_n_out,            //      .chipselect_n_out
		input  wire [3:0]  tcs1_byteenable_n_out,            //      .byteenable_n_out
		input  wire [0:0]  tcs1_outputenable_n_out,          //      .outputenable_n_out
		input  wire [0:0]  tcs1_write_n_out,                 //      .write_n_out
		input  wire [31:0] tcs1_data_out,                    //      .data_out
		output wire [31:0] tcs1_data_in,                     //      .data_in
		input  wire        tcs1_data_outen,                  //      .data_outen
		input  wire [19:0] tcs1_address_out,                 //      .address_out
		input  wire [0:0]  tcs1_reset_n_out,                 //      .reset_n_out
		input  wire [0:0]  tcs1_begintransfer_n_out,         //      .begintransfer_n_out
		input  wire        tcs2_request,                     //  tcs2.request
		output wire        tcs2_grant,                       //      .grant
		input  wire [24:0] tcs2_address_out,                 //      .address_out
		input  wire [0:0]  tcs2_read_n_out,                  //      .read_n_out
		input  wire [0:0]  tcs2_write_n_out,                 //      .write_n_out
		input  wire [15:0] tcs2_data_out,                    //      .data_out
		output wire [15:0] tcs2_data_in,                     //      .data_in
		input  wire        tcs2_data_outen,                  //      .data_outen
		input  wire [0:0]  tcs2_chipselect_n_out             //      .chipselect_n_out
	);

	wire  [2:0] arbiter_grant_data;        // arbiter:next_grant -> pin_sharer:next_grant
	wire        arbiter_grant_ready;       // pin_sharer:ack -> arbiter:ack
	wire        pin_sharer_tcs2_arb_valid; // pin_sharer:arb_ext_flash_tcm -> arbiter:sink2_valid
	wire        pin_sharer_tcs1_arb_valid; // pin_sharer:arb_max2_inf_tcm -> arbiter:sink1_valid
	wire        pin_sharer_tcs0_arb_valid; // pin_sharer:arb_ssram_tcm -> arbiter:sink0_valid

	memory_flash_tristate_bridge_pinSharer_0_pin_sharer pin_sharer (
		.clk                              (clk_clk),                          //      clk.clk
		.reset                            (reset_reset),                      //    reset.reset
		.request                          (request),                          //      tcm.request
		.grant                            (grant),                            //         .grant
		.read_n_to_the_ext_flash          (read_n_to_the_ext_flash),          //         .read_n_to_the_ext_flash_out
		.write_n_to_the_ext_flash         (write_n_to_the_ext_flash),         //         .write_n_to_the_ext_flash_out
		.select_n_to_the_ext_flash        (select_n_to_the_ext_flash),        //         .select_n_to_the_ext_flash_out
		.chipenable1_n_to_the_max2_inf    (chipenable1_n_to_the_max2_inf),    //         .chipenable1_n_to_the_max2_inf_out
		.bw_n_to_the_max2_inf             (bw_n_to_the_max2_inf),             //         .bw_n_to_the_max2_inf_out
		.outputenable_n_to_the_max2_inf   (outputenable_n_to_the_max2_inf),   //         .outputenable_n_to_the_max2_inf_out
		.bwe_n_to_the_max2_inf            (bwe_n_to_the_max2_inf),            //         .bwe_n_to_the_max2_inf_out
		.reset_n_to_the_max2_inf          (reset_n_to_the_max2_inf),          //         .reset_n_to_the_max2_inf_out
		.adsc_n_to_the_max2_inf           (adsc_n_to_the_max2_inf),           //         .adsc_n_to_the_max2_inf_out
		.chipenable1_n_to_the_ssram       (chipenable1_n_to_the_ssram),       //         .chipenable1_n_to_the_ssram_out
		.bw_n_to_the_ssram                (bw_n_to_the_ssram),                //         .bw_n_to_the_ssram_out
		.outputenable_n_to_the_ssram      (outputenable_n_to_the_ssram),      //         .outputenable_n_to_the_ssram_out
		.bwe_n_to_the_ssram               (bwe_n_to_the_ssram),               //         .bwe_n_to_the_ssram_out
		.flash_tristate_bridge_data       (flash_tristate_bridge_data),       //         .flash_tristate_bridge_data_out
		.flash_tristate_bridge_data_in    (flash_tristate_bridge_data_in),    //         .flash_tristate_bridge_data_in
		.flash_tristate_bridge_data_outen (flash_tristate_bridge_data_outen), //         .flash_tristate_bridge_data_outen
		.flash_tristate_bridge_address    (flash_tristate_bridge_address),    //         .flash_tristate_bridge_address_out
		.reset_n_to_the_ssram             (reset_n_to_the_ssram),             //         .reset_n_to_the_ssram_out
		.adsc_n_to_the_ssram              (adsc_n_to_the_ssram),              //         .adsc_n_to_the_ssram_out
		.tcs0_request                     (tcs0_request),                     //     tcs0.request
		.tcs0_grant                       (tcs0_grant),                       //         .grant
		.tcs0_tcm_chipselect_n_out        (tcs0_chipselect_n_out),            //         .chipselect_n_out
		.tcs0_tcm_byteenable_n_out        (tcs0_byteenable_n_out),            //         .byteenable_n_out
		.tcs0_tcm_outputenable_n_out      (tcs0_outputenable_n_out),          //         .outputenable_n_out
		.tcs0_tcm_write_n_out             (tcs0_write_n_out),                 //         .write_n_out
		.tcs0_tcm_data_out                (tcs0_data_out),                    //         .data_out
		.tcs0_tcm_data_in                 (tcs0_data_in),                     //         .data_in
		.tcs0_tcm_data_outen              (tcs0_data_outen),                  //         .data_outen
		.tcs0_tcm_address_out             (tcs0_address_out),                 //         .address_out
		.tcs0_tcm_reset_n_out             (tcs0_reset_n_out),                 //         .reset_n_out
		.tcs0_tcm_begintransfer_n_out     (tcs0_begintransfer_n_out),         //         .begintransfer_n_out
		.tcs1_request                     (tcs1_request),                     //     tcs1.request
		.tcs1_grant                       (tcs1_grant),                       //         .grant
		.tcs1_tcm_chipselect_n_out        (tcs1_chipselect_n_out),            //         .chipselect_n_out
		.tcs1_tcm_byteenable_n_out        (tcs1_byteenable_n_out),            //         .byteenable_n_out
		.tcs1_tcm_outputenable_n_out      (tcs1_outputenable_n_out),          //         .outputenable_n_out
		.tcs1_tcm_write_n_out             (tcs1_write_n_out),                 //         .write_n_out
		.tcs1_tcm_data_out                (tcs1_data_out),                    //         .data_out
		.tcs1_tcm_data_in                 (tcs1_data_in),                     //         .data_in
		.tcs1_tcm_data_outen              (tcs1_data_outen),                  //         .data_outen
		.tcs1_tcm_address_out             (tcs1_address_out),                 //         .address_out
		.tcs1_tcm_reset_n_out             (tcs1_reset_n_out),                 //         .reset_n_out
		.tcs1_tcm_begintransfer_n_out     (tcs1_begintransfer_n_out),         //         .begintransfer_n_out
		.tcs2_request                     (tcs2_request),                     //     tcs2.request
		.tcs2_grant                       (tcs2_grant),                       //         .grant
		.tcs2_tcm_address_out             (tcs2_address_out),                 //         .address_out
		.tcs2_tcm_read_n_out              (tcs2_read_n_out),                  //         .read_n_out
		.tcs2_tcm_write_n_out             (tcs2_write_n_out),                 //         .write_n_out
		.tcs2_tcm_data_out                (tcs2_data_out),                    //         .data_out
		.tcs2_tcm_data_in                 (tcs2_data_in),                     //         .data_in
		.tcs2_tcm_data_outen              (tcs2_data_outen),                  //         .data_outen
		.tcs2_tcm_chipselect_n_out        (tcs2_chipselect_n_out),            //         .chipselect_n_out
		.ack                              (arbiter_grant_ready),              //    grant.ready
		.next_grant                       (arbiter_grant_data),               //         .data
		.arb_ext_flash_tcm                (pin_sharer_tcs2_arb_valid),        // tcs2_arb.valid
		.arb_max2_inf_tcm                 (pin_sharer_tcs1_arb_valid),        // tcs1_arb.valid
		.arb_ssram_tcm                    (pin_sharer_tcs0_arb_valid)         // tcs0_arb.valid
	);

	memory_flash_tristate_bridge_pinSharer_0_arbiter arbiter (
		.clk         (clk_clk),                   //       clk.clk
		.reset       (reset_reset),               // clk_reset.reset
		.ack         (arbiter_grant_ready),       //     grant.ready
		.next_grant  (arbiter_grant_data),        //          .data
		.sink0_valid (pin_sharer_tcs0_arb_valid), //     sink0.valid
		.sink1_valid (pin_sharer_tcs1_arb_valid), //     sink1.valid
		.sink2_valid (pin_sharer_tcs2_arb_valid)  //     sink2.valid
	);

endmodule
